//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBridge.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicBridge.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Name Layered Design:.
        /// </summary>
        public static string _1NameLayeredDesign {
            get {
                return ResourceManager.GetString("_1NameLayeredDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Select Glamourer designs:.
        /// </summary>
        public static string _2SelectGlamourerDesigns {
            get {
                return ResourceManager.GetString("_2SelectGlamourerDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Change order if needed.
        /// </summary>
        public static string _3ChangeOrderIfNeeded {
            get {
                return ResourceManager.GetString("_3ChangeOrderIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new entry.
        /// </summary>
        public static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new preset folder.
        /// </summary>
        public static string AddNewPresetFolder {
            get {
                return ResourceManager.GetString("AddNewPresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule.
        /// </summary>
        public static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow selecting titles registered for other characters.
        /// </summary>
        public static string AllowSelectingTitlesRegisteredForOtherCharacters {
            get {
                return ResourceManager.GetString("AllowSelectingTitlesRegisteredForOtherCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and delete included profiles (Hold CTRL+SHIFT).
        /// </summary>
        public static string AndDeleteIncludedProfilesHoldCTRLSHIFT {
            get {
                return ResourceManager.GetString("AndDeleteIncludedProfilesHoldCTRLSHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and $ more.
        /// </summary>
        public static string AndMore {
            get {
                return ResourceManager.GetString("AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and move profiles to default folder (Hold CTRL).
        /// </summary>
        public static string AndMoveProfilesToDefaultFolderHoldCTRL {
            get {
                return ResourceManager.GetString("AndMoveProfilesToDefaultFolderHoldCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned profile.
        /// </summary>
        public static string AssignedProfile {
            get {
                return ResourceManager.GetString("AssignedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Type:.
        /// </summary>
        public static string AssignmentType {
            get {
                return ResourceManager.GetString("AssignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofill empty preset name with first selected plugin&apos;s option name upon selecting it.
        /// </summary>
        public static string AutofillEmptyNames {
            get {
                return ResourceManager.GetString("AutofillEmptyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autogenerated Profile for $.
        /// </summary>
        public static string AutogeneratedProfileFor {
            get {
                return ResourceManager.GetString("AutogeneratedProfileFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You MUST enable this setting or disable Glamourer&apos;s automation, otherwise either Glamourer&apos;s or DynamicBridge&apos;s automation will not work correctly..
        /// </summary>
        public static string AutomationWarning {
            get {
                return ResourceManager.GetString("AutomationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Preset.
        /// </summary>
        public static string BasePreset {
            get {
                return ResourceManager.GetString("BasePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist $1. This will prevent it from showing up for profile assignments. This will also undo profile assignments for $1. .
        /// </summary>
        public static string BlacklistCharaTooltip {
            get {
                return ResourceManager.GetString("BlacklistCharaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;$&quot; is blacklisted. Select another profile to edit it..
        /// </summary>
        public static string BlacklistedCharacter {
            get {
                return ResourceManager.GetString("BlacklistedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Censored names will change upon pressing this button..
        /// </summary>
        public static string CensorHelp {
            get {
                return ResourceManager.GetString("CensorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character blacklisted.
        /// </summary>
        public static string CharacterBlacklisted {
            get {
                return ResourceManager.GetString("CharacterBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;$&quot; has no associated profile. Select other profile to edit or associate profile in Characters tab..
        /// </summary>
        public static string CharaNoAssociation {
            get {
                return ResourceManager.GetString("CharaNoAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DynamicBridge] Glamourer automation is enabled but DynamicBridge is not configured to work together with it. This will cause issues. Either disable Glamourer automation or configure DynamicBridge accordingly (/db - settings)..
        /// </summary>
        public static string ChatNoticeGlamourerWarning {
            get {
                return ResourceManager.GetString("ChatNoticeGlamourerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open the plugin settings\n/db apply - reapply rules immediately\n/db static &lt;name&gt; - mark preset as static\n/db dynamic - cancel static preset and use dynamic rules.
        /// </summary>
        public static string CommangHelp {
            get {
                return ResourceManager.GetString("CommangHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can create layered designs for Glamourer. Upon application, they will be applied sequentially one after another. You will be able to select layered designs for profiles together with normal entries..
        /// </summary>
        public static string ComplexGlamourerHelp {
            get {
                return ResourceManager.GetString("ComplexGlamourerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure rule conditions.
        /// </summary>
        public static string ConfigureRuleConditions {
            get {
                return ResourceManager.GetString("ConfigureRuleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (copy).
        /// </summary>
        public static string CopySuffix {
            get {
                return ResourceManager.GetString("CopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (copy $).
        /// </summary>
        public static string CopySuffixWithNumber {
            get {
                return ResourceManager.GetString("CopySuffixWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this profile to clipboard.
        /// </summary>
        public static string CopyThisProfileToClipboard {
            get {
                return ResourceManager.GetString("CopyThisProfileToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import from clipboard.
        /// </summary>
        public static string CouldNotImportFromClipboard {
            get {
                return ResourceManager.GetString("CouldNotImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty.
        /// </summary>
        public static string CreateEmpty {
            get {
                return ResourceManager.GetString("CreateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new empty profile.
        /// </summary>
        public static string CreateNewEmptyProfile {
            get {
                return ResourceManager.GetString("CreateNewEmptyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new empty profile and assign it to current character.
        /// </summary>
        public static string CreateNewEmptyProfileAndAssignItToCurrentCharacter {
            get {
                return ResourceManager.GetString("CreateNewEmptyProfileAndAssignItToCurrentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Current character -.
        /// </summary>
        public static string CurrentCharacterSelectable {
            get {
                return ResourceManager.GetString("CurrentCharacterSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: $1/$2.
        /// </summary>
        public static string CurrentEmote {
            get {
                return ResourceManager.GetString("CurrentEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All registered profiles are displayed in global profile, but only ones that are assigned to your current character will be used..
        /// </summary>
        public static string CustomizePlusGlobalNotice {
            get {
                return ResourceManager.GetString("CustomizePlusGlobalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder....
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL and click to delete information about $1. This will also undo profile assignment to the character but and as soon as you relog back onto it, $1 will be registered in a plugin again..
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you will enable this option, you will be able to mark any condition with cross marker. If any condition marked with cross within the rule is matching, that entire rule is ignored..
        /// </summary>
        public static string DenyCondHelp {
            get {
                return ResourceManager.GetString("DenyCondHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If matching any condition with cross, rule will not be applied..
        /// </summary>
        public static string DenyConditionsTooltip {
            get {
                return ResourceManager.GetString("DenyConditionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow applying negative conditions.
        /// </summary>
        public static string Draw_AllowApplyingNegativeConditions {
            get {
                return ResourceManager.GetString("Draw_AllowApplyingNegativeConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown menu size.
        /// </summary>
        public static string Draw_DropdownMenuSize {
            get {
                return ResourceManager.GetString("Draw_DropdownMenuSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Plugin.
        /// </summary>
        public static string Draw_EnablePlugin {
            get {
                return ResourceManager.GetString("Draw_EnablePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Draw_General {
            get {
                return ResourceManager.GetString("Draw_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tutorial.
        /// </summary>
        public static string Draw_HideTutorial {
            get {
                return ResourceManager.GetString("Draw_HideTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicBridge behavior when no Glamourer rule is found:.
        /// </summary>
        public static string DynamicBridgeBehaviorWhenNoGlamourerRuleIsFound {
            get {
                return ResourceManager.GetString("DynamicBridgeBehaviorWhenNoGlamourerRuleIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this rule.
        /// </summary>
        public static string EnableThisRule {
            get {
                return ResourceManager.GetString("EnableThisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string ErrorNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string ErrorNameMustBeUnique {
            get {
                return ResourceManager.GetString("ErrorNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to clipboard.
        /// </summary>
        public static string ExportToClipboard {
            get {
                return ResourceManager.GetString("ExportToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable extra conditions or disable unused for convenience and performance boost..
        /// </summary>
        public static string ExtraHelp {
            get {
                return ResourceManager.GetString("ExtraHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to paste from clipboard:\n.
        /// </summary>
        public static string FailedToPasteFromClipboardN {
            get {
                return ResourceManager.GetString("FailedToPasteFromClipboardN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values from this preset will be used as default in current profile..
        /// </summary>
        public static string FallbackNotice {
            get {
                return ResourceManager.GetString("FallbackNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback preset.
        /// </summary>
        public static string FallbackPresetSection {
            get {
                return ResourceManager.GetString("FallbackPresetSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder whitelist.
        /// </summary>
        public static string FolderWhitelistColumn {
            get {
                return ResourceManager.GetString("FolderWhitelistColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force update appearance on job and gearset changes.
        /// </summary>
        public static string ForceUpdateSetting {
            get {
                return ResourceManager.GetString("ForceUpdateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force update your character, reapplying all rules and resets.
        /// </summary>
        public static string ForceUpdateYourCharacterReapplyingAllRulesAndResets {
            get {
                return ResourceManager.GetString("ForceUpdateYourCharacterReapplyingAllRulesAndResets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display full path in profile editor, where available.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ No name found.
        /// </summary>
        public static string GearsetFallbackName {
            get {
                return ResourceManager.GetString("GearsetFallbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glamourer disabled in settings. Function unavailable..
        /// </summary>
        public static string GlamourerDisabledInSettingsFunctionUnavailable {
            get {
                return ResourceManager.GetString("GlamourerDisabledInSettingsFunctionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Presets are available for use on each of your characters..
        /// </summary>
        public static string GlobalPresetsNote {
            get {
                return ResourceManager.GetString("GlobalPresetsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Beta] Restore appearance as it was before applying rule.
        /// </summary>
        public static string GuiSettings_BetaRestoreAppearanceAsItWasBeforeApplyingRule {
            get {
                return ResourceManager.GetString("GuiSettings_BetaRestoreAppearanceAsItWasBeforeApplyingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string GuiSettings_Large {
            get {
                return ResourceManager.GetString("GuiSettings_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum possible.
        /// </summary>
        public static string GuiSettings_MaximumPossible {
            get {
                return ResourceManager.GetString("GuiSettings_MaximumPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to game state.
        /// </summary>
        public static string GuiSettings_RevertToGameState {
            get {
                return ResourceManager.GetString("GuiSettings_RevertToGameState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to Glamourer&apos;s automation.
        /// </summary>
        public static string GuiSettings_RevertToGlamourerSAutomation {
            get {
                return ResourceManager.GetString("GuiSettings_RevertToGlamourerSAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string GuiSettings_Small {
            get {
                return ResourceManager.GetString("GuiSettings_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string GuiSettings_Standard {
            get {
                return ResourceManager.GetString("GuiSettings_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden from rules.
        /// </summary>
        public static string HiddenFromRules {
            get {
                return ResourceManager.GetString("HiddenFromRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide from Rules section.
        /// </summary>
        public static string HideFromRulesSection {
            get {
                return ResourceManager.GetString("HideFromRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL and click to delete.
        /// </summary>
        public static string HoldCTRLAndClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLAndClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL+Click to delete.
        /// </summary>
        public static string HoldCTRLClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL key and click to unassign profile $1 from $2..
        /// </summary>
        public static string HoldCTRLKeyAndClickToUnassignProfile1From2 {
            get {
                return ResourceManager.GetString("HoldCTRLKeyAndClickToUnassignProfile1From2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All registered titles are displayed in global profile, but only ones that are assigned to your current character will be used UNLESS &quot;Allow selecting titles registered for other characters&quot; is enabled in settings..
        /// </summary>
        public static string HonorificGlobalPresetNotice {
            get {
                return ResourceManager.GetString("HonorificGlobalPresetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current house: $.
        /// </summary>
        public static string HouseReg_Draw_CurrentHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_CurrentHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register this house.
        /// </summary>
        public static string HouseReg_Draw_RegisterThisHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_RegisterThisHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in house.
        /// </summary>
        public static string HouseReg_Draw_YouAreNotInHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_YouAreNotInHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can register a house. After registration, you will be able to select it as a condition in Dynamic Rules tab..
        /// </summary>
        public static string HouseRegHelp {
            get {
                return ResourceManager.GetString("HouseRegHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IDColumn {
            get {
                return ResourceManager.GetString("IDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Censor Seed.
        /// </summary>
        public static string IncognitoCensor {
            get {
                return ResourceManager.GetString("IncognitoCensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Beta] Enable Incognito Mode (WORK IN PROGRESS, ONLY HIDES IN SOME PLACES YET).
        /// </summary>
        public static string IncognitoEnable {
            get {
                return ResourceManager.GetString("IncognitoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces your character name with random animal name and your world name with random fantasy world name. Same name will always generate same counterparts, for you but not for other people. Additionally, hides text in input fields and shows temporary profile/preset ID instead of name..
        /// </summary>
        public static string IncognitoHelp {
            get {
                return ResourceManager.GetString("IncognitoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only replacement words with same first letter as original when possible..
        /// </summary>
        public static string IncognitoReplacement {
            get {
                return ResourceManager.GetString("IncognitoReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! No names will be censored in Log and Debug tabs and Dalamud.log! \nWarning! If you share configuration file AND censored name, original name CAN BE RESTORED. If you need to send configuration file and ensure that you remain anonymous, click Regenerate Censor Seed button, send configuration and click the button again..
        /// </summary>
        public static string IncognitoWarning {
            get {
                return ResourceManager.GetString("IncognitoWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can individually enable/disable plugin integrations and configure appropriate related settings..
        /// </summary>
        public static string IntegrationsHelp {
            get {
                return ResourceManager.GetString("IntegrationsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not used by &quot;$&quot;..
        /// </summary>
        public static string ItIsNotUsedBy {
            get {
                return ResourceManager.GetString("ItIsNotUsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord for support and changelogs.
        /// </summary>
        public static string JoinDiscordForSupportAndChangelogs {
            get {
                return ResourceManager.GetString("JoinDiscordForSupportAndChangelogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layered Designs.
        /// </summary>
        public static string LayeredDesigns {
            get {
                return ResourceManager.GetString("LayeredDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because plugin version was changed, a backup of your current configuraton has been created..
        /// </summary>
        public static string LogNoticeVersionChange {
            get {
                return ResourceManager.GetString("LogNoticeVersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by NightmareXIV in collaboration with AsunaTsuki.
        /// </summary>
        public static string MadeByNightmareXIVInCollaborationWithAsunaTsuki {
            get {
                return ResourceManager.GetString("MadeByNightmareXIVInCollaborationWithAsunaTsuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main presets.
        /// </summary>
        public static string MainPresetsFolder {
            get {
                return ResourceManager.GetString("MainPresetsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting any of the following conditions will result in rule being triggered:\n.
        /// </summary>
        public static string MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN {
            get {
                return ResourceManager.GetString("MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting any of these condition will make rule invalid:.
        /// </summary>
        public static string MeetingAnyOfTheseConditionWillMakeRuleInvalid {
            get {
                return ResourceManager.GetString("MeetingAnyOfTheseConditionWillMakeRuleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle Presets.
        /// </summary>
        public static string MoodlePresets {
            get {
                return ResourceManager.GetString("MoodlePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of these Moodles/Presets will be applied:\n$.
        /// </summary>
        public static string MoodlesApplicationTooltip {
            get {
                return ResourceManager.GetString("MoodlesApplicationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this moodle(s) once preset is no longer applied.
        /// </summary>
        public static string MoodlesCancelTooltip {
            get {
                return ResourceManager.GetString("MoodlesCancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Main folder -.
        /// </summary>
        public static string MoveToMainFolder {
            get {
                return ResourceManager.GetString("MoveToMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile $.
        /// </summary>
        public static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile from data in clipboard.
        /// </summary>
        public static string NewProfilePasteTooltip {
            get {
                return ResourceManager.GetString("NewProfilePasteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No associated profile.
        /// </summary>
        public static string NoAssociatedProfile {
            get {
                return ResourceManager.GetString("NoAssociatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - None -.
        /// </summary>
        public static string NoneSelection {
            get {
                return ResourceManager.GetString("NoneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - No profile -.
        /// </summary>
        public static string NoProfileSelectable {
            get {
                return ResourceManager.GetString("NoProfileSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character blacklisted or not logged in..
        /// </summary>
        public static string NoticeCharacterBlacklistedOrNotLoggedIn {
            get {
                return ResourceManager.GetString("NoticeCharacterBlacklistedOrNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find preset $..
        /// </summary>
        public static string NoticeNotFound {
            get {
                return ResourceManager.GetString("NoticeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ was made static..
        /// </summary>
        public static string NotifyWasMadeStatic {
            get {
                return ResourceManager.GetString("NotifyWasMadeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not installed.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 | $2 selected.
        /// </summary>
        public static string NotListSelected {
            get {
                return ResourceManager.GetString("NotListSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected.
        /// </summary>
        public static string OnlySelected {
            get {
                return ResourceManager.GetString("OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open allow list editor.
        /// </summary>
        public static string OpenAllowListEditor {
            get {
                return ResourceManager.GetString("OpenAllowListEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open deny list editor.
        /// </summary>
        public static string OpenDenyListEditor {
            get {
                return ResourceManager.GetString("OpenDenyListEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable passthrough for this rule. DynamicBridge will continue searching after encountering this rule. All valid found rules will be applied one after another sequentially..
        /// </summary>
        public static string PassthroughTooltip {
            get {
                return ResourceManager.GetString("PassthroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Clipboard.
        /// </summary>
        public static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste previously copied preset from clipboard.
        /// </summary>
        public static string PastePreviouslyCopiedPresetFromClipboard {
            get {
                return ResourceManager.GetString("PastePreviouslyCopiedPresetFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste rule from Clipboard.
        /// </summary>
        public static string PasteRuleFromClipboard {
            get {
                return ResourceManager.GetString("PasteRuleFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUGIN DISABLED BY SETTINGS.
        /// </summary>
        public static string PLUGINDISABLEDBYSETTINGS {
            get {
                return ResourceManager.GetString("PLUGINDISABLEDBYSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset $ is selected as static. Automation disabled..
        /// </summary>
        public static string PresetIsSelectedAsStaticAutomationDisabled {
            get {
                return ResourceManager.GetString("PresetIsSelectedAsStaticAutomationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name.
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new empty preset into default or focused folder.
        /// </summary>
        public static string Presets_AddNewEmpty {
            get {
                return ResourceManager.GetString("Presets.AddNewEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset folder $.
        /// </summary>
        public static string Presets_PresetFolder {
            get {
                return ResourceManager.GetString("Presets_PresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this preset as static, applying it unconditionally on this character disregarding any rules..
        /// </summary>
        public static string PresetStaticSetNotice {
            get {
                return ResourceManager.GetString("PresetStaticSetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile $.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read instructions and FAQ.
        /// </summary>
        public static string ReadInstructionsAndFAQ {
            get {
                return ResourceManager.GetString("ReadInstructionsAndFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow DynamicBridge to manage Glamourer&apos;s automation setting.
        /// </summary>
        public static string ReflectAutomation {
            get {
                return ResourceManager.GetString("ReflectAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this setting is enabled, Glamourer&apos;s global automation setting will be automatically disabled upon applying any rule and will be automatically enabled when no rules are found..
        /// </summary>
        public static string ReflectAutomationHelp {
            get {
                return ResourceManager.GetString("ReflectAutomationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue, request feature or ask a question on GitHub.
        /// </summary>
        public static string ReportIssueRequestFeatureOrAskAQuestionOnGitHub {
            get {
                return ResourceManager.GetString("ReportIssueRequestFeatureOrAskAQuestionOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert character before applying rule.
        /// </summary>
        public static string RevertCharacterBeforeApplyingRule {
            get {
                return ResourceManager.GetString("RevertCharacterBeforeApplyingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert character before restoring automation.
        /// </summary>
        public static string RevertCharacterBeforeRestoringAutomation {
            get {
                return ResourceManager.GetString("RevertCharacterBeforeRestoringAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to Automation is recommended if you are using Glamourer automation..
        /// </summary>
        public static string RevertTooltip {
            get {
                return ResourceManager.GetString("RevertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to open context menu.
        /// </summary>
        public static string RightClickToOpenContextMenu {
            get {
                return ResourceManager.GetString("RightClickToOpenContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biome.
        /// </summary>
        public static string RuleBiome {
            get {
                return ResourceManager.GetString("RuleBiome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        public static string RuleEmote {
            get {
                return ResourceManager.GetString("RuleEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset.
        /// </summary>
        public static string RuleGearset {
            get {
                return ResourceManager.GetString("RuleGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string RuleHouse {
            get {
                return ResourceManager.GetString("RuleHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string RuleJob {
            get {
                return ResourceManager.GetString("RuleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string RulePreset {
            get {
                return ResourceManager.GetString("RulePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string RuleState {
            get {
                return ResourceManager.GetString("RuleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string RuleTime {
            get {
                return ResourceManager.GetString("RuleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string RuleWeather {
            get {
                return ResourceManager.GetString("RuleWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string RuleWorld {
            get {
                return ResourceManager.GetString("RuleWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string RuleZone {
            get {
                return ResourceManager.GetString("RuleZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Group.
        /// </summary>
        public static string RuleZoneGroup {
            get {
                return ResourceManager.GetString("RuleZoneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search character name....
        /// </summary>
        public static string SearchCharacterName {
            get {
                return ResourceManager.GetString("SearchCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search profile name....
        /// </summary>
        public static string SearchProfileName {
            get {
                return ResourceManager.GetString("SearchProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select allow list zones.
        /// </summary>
        public static string SelectAllowListZones {
            get {
                return ResourceManager.GetString("SelectAllowListZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select deny list zones.
        /// </summary>
        public static string SelectDenyListZones {
            get {
                return ResourceManager.GetString("SelectDenyListZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this profile for editing.
        /// </summary>
        public static string SelectThisProfileForEditing {
            get {
                return ResourceManager.GetString("SelectThisProfileForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Rules section.
        /// </summary>
        public static string ShowInRulesSection {
            get {
                return ResourceManager.GetString("ShowInRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split base classes and jobs.
        /// </summary>
        public static string SplitBaseClassesAndJobs {
            get {
                return ResourceManager.GetString("SplitBaseClassesAndJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string TabCharacters {
            get {
                return ResourceManager.GetString("TabCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Rules.
        /// </summary>
        public static string TabDynamicRules {
            get {
                return ResourceManager.GetString("TabDynamicRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Presets.
        /// </summary>
        public static string TabGlobalPresets {
            get {
                return ResourceManager.GetString("TabGlobalPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Registration.
        /// </summary>
        public static string TabHouseRegistration {
            get {
                return ResourceManager.GetString("TabHouseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string TabPresets {
            get {
                return ResourceManager.GetString("TabPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string TabProfiles {
            get {
                return ResourceManager.GetString("TabProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string TabTutorial {
            get {
                return ResourceManager.GetString("TabTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DynamicBridge plugin!
        ///This plugin allows you to dynamically change your Glamourer, Customize+ and Honorific presets based on various rules. You can use this plugin for simple means such as switching your appearance manually or you can create very advanced and precise rule sets.
        ///---
        ///If you have previously used older version of the plugin, your configuration has been converted to use more convenient profile system. In case something went wrong, a backup of your old configuration file has been ta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblacklist this character..
        /// </summary>
        public static string UnblacklistThisCharacter {
            get {
                return ResourceManager.GetString("UnblacklistThisCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown character $.
        /// </summary>
        public static string UnknownCharacter {
            get {
                return ResourceManager.GetString("UnknownCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported version.
        /// </summary>
        public static string UnsupportedVersion {
            get {
                return ResourceManager.GetString("UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by.
        /// </summary>
        public static string UsedByColumn {
            get {
                return ResourceManager.GetString("UsedByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using dynamic rules now..
        /// </summary>
        public static string UsingDynamicRulesNow {
            get {
                return ResourceManager.GetString("UsingDynamicRulesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be randomly selected between:\n.
        /// </summary>
        public static string WillBeRandomlySelectedBetween {
            get {
                return ResourceManager.GetString("WillBeRandomlySelectedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are editing profile &quot;$&quot;. .
        /// </summary>
        public static string YouAreEditingProfile {
            get {
                return ResourceManager.GetString("YouAreEditingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are editing profile &quot;$1&quot; which is used by &quot;$2&quot;..
        /// </summary>
        public static string YouAreEditingProfile1WhichIsUsedBy2 {
            get {
                return ResourceManager.GetString("YouAreEditingProfile1WhichIsUsedBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in. Please select profile to edit..
        /// </summary>
        public static string YouAreNotLoggedInPleaseSelectProfileToEdit {
            get {
                return ResourceManager.GetString("YouAreNotLoggedInPleaseSelectProfileToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current character is blacklisted.
        /// </summary>
        public static string YourCurrentCharacterIsBlacklisted {
            get {
                return ResourceManager.GetString("YourCurrentCharacterIsBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone group.
        /// </summary>
        public static string ZoneGroup {
            get {
                return ResourceManager.GetString("ZoneGroup", resourceCulture);
            }
        }
    }
}
