//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBridge.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicBridge.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new preset folder.
        /// </summary>
        public static string AddNewPresetFolder {
            get {
                return ResourceManager.GetString("AddNewPresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and delete included profiles (Hold CTRL+SHIFT).
        /// </summary>
        public static string AndDeleteIncludedProfilesHoldCTRLSHIFT {
            get {
                return ResourceManager.GetString("AndDeleteIncludedProfilesHoldCTRLSHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and $ more.
        /// </summary>
        public static string AndMore {
            get {
                return ResourceManager.GetString("AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and move profiles to default folder (Hold CTRL).
        /// </summary>
        public static string AndMoveProfilesToDefaultFolderHoldCTRL {
            get {
                return ResourceManager.GetString("AndMoveProfilesToDefaultFolderHoldCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Type:.
        /// </summary>
        public static string AssignmentType {
            get {
                return ResourceManager.GetString("AssignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Preset.
        /// </summary>
        public static string BasePreset {
            get {
                return ResourceManager.GetString("BasePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;$\&quot; is blacklisted. Select another profile to edit it..
        /// </summary>
        public static string BlacklistedCharacter {
            get {
                return ResourceManager.GetString("BlacklistedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character blacklisted.
        /// </summary>
        public static string CharacterBlacklisted {
            get {
                return ResourceManager.GetString("CharacterBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;$\&quot; has no associated profile. Select other profile to edit or associate profile in Characters tab..
        /// </summary>
        public static string CharaNoAssociation {
            get {
                return ResourceManager.GetString("CharaNoAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (copy).
        /// </summary>
        public static string CopySuffix {
            get {
                return ResourceManager.GetString("CopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (copy $).
        /// </summary>
        public static string CopySuffixWithNumber {
            get {
                return ResourceManager.GetString("CopySuffixWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this profile to clipboard.
        /// </summary>
        public static string CopyThisProfileToClipboard {
            get {
                return ResourceManager.GetString("CopyThisProfileToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import from clipboard.
        /// </summary>
        public static string CouldNotImportFromClipboard {
            get {
                return ResourceManager.GetString("CouldNotImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Empty.
        /// </summary>
        public static string CreateEmpty {
            get {
                return ResourceManager.GetString("CreateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new empty profile.
        /// </summary>
        public static string CreateNewEmptyProfile {
            get {
                return ResourceManager.GetString("CreateNewEmptyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All registered profiles are displayed in global profile, but only ones that are assigned to your current character will be used..
        /// </summary>
        public static string CustomizePlusGlobalNotice {
            get {
                return ResourceManager.GetString("CustomizePlusGlobalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder....
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        public static string ErrorNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string ErrorNameMustBeUnique {
            get {
                return ResourceManager.GetString("ErrorNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to clipboard.
        /// </summary>
        public static string ExportToClipboard {
            get {
                return ResourceManager.GetString("ExportToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values from this preset will be used as default in current profile..
        /// </summary>
        public static string FallbackNotice {
            get {
                return ResourceManager.GetString("FallbackNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback preset.
        /// </summary>
        public static string FallbackPresetSection {
            get {
                return ResourceManager.GetString("FallbackPresetSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder whitelist.
        /// </summary>
        public static string FolderWhitelistColumn {
            get {
                return ResourceManager.GetString("FolderWhitelistColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Presets are available for use on each of your characters..
        /// </summary>
        public static string GlobalPresetsNote {
            get {
                return ResourceManager.GetString("GlobalPresetsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden from rules.
        /// </summary>
        public static string HiddenFromRules {
            get {
                return ResourceManager.GetString("HiddenFromRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide from Rules section.
        /// </summary>
        public static string HideFromRulesSection {
            get {
                return ResourceManager.GetString("HideFromRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL and click to delete.
        /// </summary>
        public static string HoldCTRLAndClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLAndClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL+Click to delete.
        /// </summary>
        public static string HoldCTRLClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All registered titles are displayed in global profile, but only ones that are assigned to your current character will be used UNLESS \&quot;Allow selecting titles registered for other characters\&quot; is enabled in settings..
        /// </summary>
        public static string HonorificGlobalPresetNotice {
            get {
                return ResourceManager.GetString("HonorificGlobalPresetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All registered titles are displayed in global profile, but only ones that are assigned to your current character will be used UNLESS \.
        /// </summary>
        public static string HonotificGlobalProfileNotice {
            get {
                return ResourceManager.GetString("HonotificGlobalProfileNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layered Designs.
        /// </summary>
        public static string LayeredDesigns {
            get {
                return ResourceManager.GetString("LayeredDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main presets.
        /// </summary>
        public static string MainPresetsFolder {
            get {
                return ResourceManager.GetString("MainPresetsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting any of the following conditions will result in rule being triggered:\n.
        /// </summary>
        public static string MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN {
            get {
                return ResourceManager.GetString("MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle Presets.
        /// </summary>
        public static string MoodlePresets {
            get {
                return ResourceManager.GetString("MoodlePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of these Moodles/Presets will be applied:\n$.
        /// </summary>
        public static string MoodlesApplicationTooltip {
            get {
                return ResourceManager.GetString("MoodlesApplicationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this moodle(s) once preset is no longer applied.
        /// </summary>
        public static string MoodlesCancelTooltip {
            get {
                return ResourceManager.GetString("MoodlesCancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Main folder -.
        /// </summary>
        public static string MoveToMainFolder {
            get {
                return ResourceManager.GetString("MoveToMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile $.
        /// </summary>
        public static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile from data in clipboard.
        /// </summary>
        public static string NewProfilePasteTooltip {
            get {
                return ResourceManager.GetString("NewProfilePasteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No associated profile.
        /// </summary>
        public static string NoAssociatedProfile {
            get {
                return ResourceManager.GetString("NoAssociatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - None -.
        /// </summary>
        public static string NoneSelection {
            get {
                return ResourceManager.GetString("NoneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected.
        /// </summary>
        public static string OnlySelected {
            get {
                return ResourceManager.GetString("OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Clipboard.
        /// </summary>
        public static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste previously copied preset from clipboard.
        /// </summary>
        public static string PastePreviouslyCopiedPresetFromClipboard {
            get {
                return ResourceManager.GetString("PastePreviouslyCopiedPresetFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUGIN DISABLED BY SETTINGS.
        /// </summary>
        public static string PLUGINDISABLEDBYSETTINGS {
            get {
                return ResourceManager.GetString("PLUGINDISABLEDBYSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name.
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new empty preset into default or focused folder.
        /// </summary>
        public static string Presets_AddNewEmpty {
            get {
                return ResourceManager.GetString("Presets.AddNewEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset folder $.
        /// </summary>
        public static string Presets_PresetFolder {
            get {
                return ResourceManager.GetString("Presets_PresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this preset as static, applying it unconditionally on this character disregarding any rules..
        /// </summary>
        public static string PresetStaticSetNotice {
            get {
                return ResourceManager.GetString("PresetStaticSetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile $.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to open context menu.
        /// </summary>
        public static string RightClickToOpenContextMenu {
            get {
                return ResourceManager.GetString("RightClickToOpenContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search profile name....
        /// </summary>
        public static string SearchProfileName {
            get {
                return ResourceManager.GetString("SearchProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this profile for editing.
        /// </summary>
        public static string SelectThisProfileForEditing {
            get {
                return ResourceManager.GetString("SelectThisProfileForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Rules section.
        /// </summary>
        public static string ShowInRulesSection {
            get {
                return ResourceManager.GetString("ShowInRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string TabCharacters {
            get {
                return ResourceManager.GetString("TabCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Rules.
        /// </summary>
        public static string TabDynamicRules {
            get {
                return ResourceManager.GetString("TabDynamicRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Presets.
        /// </summary>
        public static string TabGlobalPresets {
            get {
                return ResourceManager.GetString("TabGlobalPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Registration.
        /// </summary>
        public static string TabHouseRegistration {
            get {
                return ResourceManager.GetString("TabHouseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string TabPresets {
            get {
                return ResourceManager.GetString("TabPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string TabProfiles {
            get {
                return ResourceManager.GetString("TabProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string TabTutorial {
            get {
                return ResourceManager.GetString("TabTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblacklist this character..
        /// </summary>
        public static string UnblacklistThisCharacter {
            get {
                return ResourceManager.GetString("UnblacklistThisCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by.
        /// </summary>
        public static string UsedByColumn {
            get {
                return ResourceManager.GetString("UsedByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be randomly selected between:\n.
        /// </summary>
        public static string WillBeRandomlySelectedBetween {
            get {
                return ResourceManager.GetString("WillBeRandomlySelectedBetween", resourceCulture);
            }
        }
    }
}
